# Site settings
title: 10 contre 11
email: d@10contre11.fr
description: "A 10 contre 11, des chiffres et du football."
baseurl: ""
url: "10contre11.fr"

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-assets
