# Site settings
title: 10 contre 11
email: damien@10contre11.fr
description: "A 10 contre 11, on joue au football avec les chiffres."
baseurl: ""
url: "10contre11.fr"

# Build settings
markdown: kramdown
permalink: pretty
